"""IBus text injection backend: atomic text insertion via input method."""
from __future__ import annotations

import logging
import os
import shutil
import socket
import subprocess
import stat
import sys
from pathlib import Path

from voiceio.backends import ProbeResult
from voiceio.ibus import SOCKET_PATH

log = logging.getLogger(__name__)
COMPONENT_DIR = Path.home() / ".local" / "share" / "ibus" / "component"
COMPONENT_DEST = COMPONENT_DIR / "voiceio.xml"
LAUNCHER_DIR = Path.home() / ".local" / "share" / "voiceio"
LAUNCHER_PATH = LAUNCHER_DIR / "voiceio-ibus-engine"
PING_TIMEOUT = 2.0


def _find_system_python() -> str:
    """Find the system Python 3 interpreter.

    IBus GObject bindings (gi) are system packages, so we need the system
    Python, not a venv or pipx Python.
    """
    # Check well-known system locations first (never a venv)
    for path in ("/usr/bin/python3", "/usr/bin/python"):
        if os.path.isfile(path) and os.access(path, os.X_OK):
            return path
    # Fallback: whatever python3 resolves to, excluding venvs
    which = shutil.which("python3")
    if which and "venv" not in which and "pipx" not in which:
        return which
    return "/usr/bin/python3"


# Resolved once at import time so probe() / install_component() use the same value.
SYSTEM_PYTHON = _find_system_python()


def _gnome_source_configured() -> bool:
    """Check if voiceio is in GNOME input sources."""
    from voiceio.platform import detect
    if not detect().is_gnome:
        return True  # non-GNOME: no input source needed
    try:
        result = subprocess.run(
            ["gsettings", "get", "org.gnome.desktop.input-sources", "sources"],
            capture_output=True, text=True, timeout=3,
        )
        return result.returncode == 0 and "('ibus', 'voiceio')" in result.stdout
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return True  # can't check, assume OK


def _has_ibus_gi() -> bool:
    """Check if system Python has IBus GObject bindings."""
    try:
        result = subprocess.run(
            [SYSTEM_PYTHON, "-c", "import gi; gi.require_version('IBus', '1.0')"],
            capture_output=True, timeout=5,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _ibus_daemon_running() -> bool:
    """Check if the IBus daemon (ibus-daemon) is running."""
    try:
        result = subprocess.run(
            ["ibus", "address"], capture_output=True, text=True, timeout=3,
        )
        return result.returncode == 0 and bool(result.stdout.strip())
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _component_installed() -> bool:
    """Check if the VoiceIO IBus component XML is installed."""
    return COMPONENT_DEST.exists() and LAUNCHER_PATH.exists()


def _get_pkg_root() -> str:
    """Get the directory that contains the ``voiceio`` package.

    For a normal pip/pipx install this is the site-packages directory.
    For an editable (``pip install -e .``) or bare git-clone this is the
    project source root.  Either way, adding the returned path to
    PYTHONPATH lets ``python -m voiceio.ibus.engine`` work.
    """
    # Path(__file__) -> .../voiceio/typers/ibus.py
    # .parent        -> .../voiceio/typers/
    # .parent        -> .../voiceio/           (the package dir)
    # .parent        -> .../                   (site-packages or source root)
    return str(Path(__file__).resolve().parent.parent.parent)


def install_component() -> bool:
    """Install the IBus engine launcher and component XML.

    Creates a launcher script (with PYTHONPATH baked in) and a component XML
    that points to it, then refreshes the IBus cache and restarts IBus.

    Returns True if installed successfully.
    """
    pkg_root = _get_pkg_root()

    # The Python that is running *right now* has voiceio installed. Record
    # its site-packages (or source root) so the launcher can find voiceio
    # even when launched by the system Python (which needs GObject/IBus
    # bindings from the system packages).
    #
    # We also record the *current* Python as a fallback. If the system
    # Python cannot import voiceio, the launcher will try the installing
    # Python directly.
    installing_python = sys.executable or "python3"

    # Create launcher script
    LAUNCHER_DIR.mkdir(parents=True, exist_ok=True)
    launcher_content = f"""#!/bin/bash
# Generated by voiceio. Do not edit manually.
# voiceio package root baked in at install time:
VOICEIO_PKG_ROOT="{pkg_root}"

# Prefer the system Python (has GObject / IBus bindings).
SYSTEM_PY="{SYSTEM_PYTHON}"
# The Python that installed voiceio (fallback).
INSTALL_PY="{installing_python}"

# Add voiceio's package root so the system Python can import it.
export PYTHONPATH="${{VOICEIO_PKG_ROOT}}:${{PYTHONPATH}}"

# Try system Python first (needed for gi / IBus bindings).
if "$SYSTEM_PY" -c "import voiceio" 2>/dev/null; then
    exec "$SYSTEM_PY" -m voiceio.ibus.engine "$@"
fi

# Fallback: the Python that installed voiceio (may be a venv/pipx Python
# that already has gi accessible via system site-packages).
exec "$INSTALL_PY" -m voiceio.ibus.engine "$@"
"""
    LAUNCHER_PATH.write_text(launcher_content)
    LAUNCHER_PATH.chmod(LAUNCHER_PATH.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    log.info("Installed IBus engine launcher to %s", LAUNCHER_PATH)

    # Write component XML pointing to launcher
    component_xml = f"""<?xml version="1.0" encoding="utf-8"?>
<component>
    <name>org.voiceio.ibus</name>
    <description>VoiceIO voice input</description>
    <exec>{LAUNCHER_PATH}</exec>
    <version>1.0</version>
    <author>voiceio</author>
    <license>MIT</license>
    <textdomain>voiceio</textdomain>
    <engines>
        <engine>
            <name>voiceio</name>
            <language>other</language>
            <license>MIT</license>
            <author>voiceio</author>
            <layout>us</layout>
            <longname>VoiceIO</longname>
            <description>Voice-to-text input</description>
            <rank>0</rank>
        </engine>
    </engines>
</component>
"""
    COMPONENT_DIR.mkdir(parents=True, exist_ok=True)
    COMPONENT_DEST.write_text(component_xml)
    log.info("Installed IBus component to %s", COMPONENT_DEST)

    # IBus needs IBUS_COMPONENT_PATH to scan ~/.local/share/ibus/component/
    ibus_env = _ibus_env()

    # Refresh IBus cache and restart so it discovers the new engine
    try:
        subprocess.run(
            ["ibus", "write-cache"], capture_output=True, timeout=5, env=ibus_env,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    try:
        subprocess.run(
            ["ibus", "restart"], capture_output=True, timeout=5, env=ibus_env,
        )
        log.info("IBus restarted with IBUS_COMPONENT_PATH")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        log.warning("Could not restart IBus. Restart manually: ibus restart")

    # Persist IBUS_COMPONENT_PATH so it survives reboot
    _persist_ibus_env()

    return True


def _ibus_env() -> dict[str, str]:
    """Build environment with IBUS_COMPONENT_PATH including user component dir."""
    env = os.environ.copy()
    system_dir = "/usr/share/ibus/component"
    user_dir = str(COMPONENT_DIR)
    env["IBUS_COMPONENT_PATH"] = f"{user_dir}:{system_dir}"
    return env


def _persist_ibus_env() -> None:
    """Write IBUS_COMPONENT_PATH to environment.d so it survives reboot.

    See systemd environment.d(5). Files in ~/.config/environment.d/ are
    loaded by systemd user services and login sessions.
    """
    env_dir = Path.home() / ".config" / "environment.d"
    env_file = env_dir / "voiceio.conf"
    system_dir = "/usr/share/ibus/component"
    user_dir = str(COMPONENT_DIR)
    content = f"IBUS_COMPONENT_PATH={user_dir}:{system_dir}\n"

    try:
        if env_file.exists() and env_file.read_text() == content:
            return  # already persisted
        env_dir.mkdir(parents=True, exist_ok=True)
        env_file.write_text(content)
        log.info("Persisted IBUS_COMPONENT_PATH to %s", env_file)
    except OSError as e:
        log.debug("Could not persist IBUS_COMPONENT_PATH: %s", e)


def _ensure_gnome_input_source() -> None:
    """Add ('ibus', 'voiceio') to GNOME input sources if running GNOME."""
    from voiceio.platform import detect
    if not detect().is_gnome:
        return

    try:
        result = subprocess.run(
            ["gsettings", "get", "org.gnome.desktop.input-sources", "sources"],
            capture_output=True, text=True, timeout=3,
        )
        if result.returncode != 0:
            return
        current = result.stdout.strip()
        if "('ibus', 'voiceio')" in current:
            log.debug("VoiceIO already in GNOME input sources")
            return

        # Parse current sources and append voiceio
        # Format: [('xkb', 'us'), ('xkb', 'fr')]
        if current.startswith("@as"):
            # Empty array
            new_sources = "[('ibus', 'voiceio')]"
        elif current == "[]":
            new_sources = "[('ibus', 'voiceio')]"
        else:
            # Insert voiceio at the end (keep current keyboard as default)
            new_sources = current.rstrip("]") + ", ('ibus', 'voiceio')]"

        subprocess.run(
            ["gsettings", "set", "org.gnome.desktop.input-sources", "sources", new_sources],
            capture_output=True, text=True, timeout=3,
        )
        log.info("Added VoiceIO to GNOME input sources: %s", new_sources)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass


class IBusTyper:
    """IBus preedit for streaming preview, IBus commit for final text.

    Also copies committed text to clipboard so terminal users (where IBus
    doesn't reach) can Ctrl+Shift+V to paste.  When the IBus engine reports
    that no client has focus (e.g. terminal emulators), we auto-paste via
    ydotool/wtype so the user doesn't have to paste manually.
    """

    name = "ibus"

    def __init__(self, platform=None, **kwargs):
        self._wl_copy = shutil.which("wl-copy")
        self._ydotool = shutil.which("ydotool")
        self._wtype = shutil.which("wtype")
        self._sock: socket.socket | None = None
        self._wl_copy_proc: subprocess.Popen | None = None

    def probe(self) -> ProbeResult:
        from voiceio.platform import pkg_install
        if not shutil.which("ibus"):
            return ProbeResult(
                ok=False,
                reason="ibus not installed",
                fix_hint=pkg_install("ibus"),
            )

        if not _has_ibus_gi():
            return ProbeResult(
                ok=False,
                reason="IBus Python bindings not available for system Python",
                fix_hint=pkg_install("gir1.2-ibus-1.0", "python3-gi"),
            )

        if not _ibus_daemon_running():
            return ProbeResult(
                ok=False,
                reason="IBus daemon not running",
                fix_hint="ibus-daemon -drxR",
            )

        if not _component_installed():
            if install_component():
                log.info("Auto-installed IBus component")
            else:
                return ProbeResult(
                    ok=False,
                    reason="VoiceIO IBus component not installed",
                    fix_hint="Run 'voiceio setup' to install",
                )

        if not _gnome_source_configured():
            return ProbeResult(
                ok=False,
                reason="VoiceIO not in GNOME input sources",
                fix_hint="Run 'voiceio setup' to configure",
            )

        return ProbeResult(ok=True)

    def type_text(self, text: str) -> None:
        if not text:
            return
        self._send(f"commit:{text}")
        self._copy_to_clipboard(text)
        if not self._engine_has_focus():
            self._simulate_paste()

    def delete_chars(self, n: int) -> None:
        pass  # Not needed: preedit handles corrections atomically

    def update_preedit(self, text: str) -> None:
        self._send(f"preedit:{text}")

    def commit_text(self, text: str) -> None:
        """Clear preedit and commit via IBus. Also copies to clipboard."""
        if not text:
            self._send("clear")
            return
        log.debug("Committing via IBus (%d chars)", len(text))
        self._send(f"commit:{text}")
        self._copy_to_clipboard(text)
        if not self._engine_has_focus():
            self._simulate_paste()

    def clear_preedit(self) -> None:
        self._send("clear")

    def _send(self, msg: str) -> None:
        """Send a command to the IBus engine via Unix DGRAM socket."""
        try:
            if self._sock is None:
                self._sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
            self._sock.sendto(msg.encode("utf-8"), str(SOCKET_PATH))
        except OSError as e:
            log.warning("IBus engine not reachable: %s", e)
            # Reset socket on error so next call retries
            if self._sock is not None:
                self._sock.close()
                self._sock = None

    def _engine_has_focus(self) -> bool:
        """Ask the IBus engine whether it has input focus in the active window."""
        try:
            sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
            sock.settimeout(0.3)
            sock.bind("")  # autobind for receiving reply
            sock.sendto(b"focus?", str(SOCKET_PATH))
            data, _ = sock.recvfrom(64)
            sock.close()
            return data == b"focused"
        except (OSError, socket.timeout):
            return True  # assume focused on error (safe default: no extra paste)

    def _simulate_paste(self) -> None:
        """Simulate Ctrl+V to paste clipboard into non-IBus apps (terminals)."""
        try:
            if self._ydotool:
                # ydotool key scancodes: 29=LCtrl, 47=V
                subprocess.run(
                    [self._ydotool, "key", "29:1", "47:1", "47:0", "29:0"],
                    capture_output=True, timeout=3,
                )
            elif self._wtype:
                subprocess.run(
                    [self._wtype, "-M", "ctrl", "-k", "v", "-m", "ctrl"],
                    capture_output=True, timeout=3,
                )
            else:
                log.debug("No paste tool available (ydotool/wtype)")
        except (subprocess.TimeoutExpired, OSError) as e:
            log.debug("Paste simulation failed: %s", e)

    def _copy_to_clipboard(self, text: str) -> None:
        """Copy text to clipboard as backup for non-IBus apps (terminals).

        Fire-and-forget. wl-copy stays alive to serve paste requests.
        Kill previous instance to avoid accumulating processes.
        """
        if not self._wl_copy:
            return
        # Kill previous wl-copy (it's replaced by the new one)
        if self._wl_copy_proc is not None:
            try:
                self._wl_copy_proc.kill()
            except OSError:
                pass
        try:
            proc = subprocess.Popen(
                ["wl-copy"],
                stdin=subprocess.PIPE, stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            proc.stdin.write(text.encode())
            proc.stdin.close()
            self._wl_copy_proc = proc
        except OSError as e:
            log.debug("wl-copy failed to start: %s", e)
